### ISSUE TITLE
Seurat objects don't contain the raw count data

### ISSUE THREAD

**Issue by SirKuikka** [Coolgenome/TCM#3]
Hi,

Thank you for sharing the Seurat objects with us. I downloaded the Seurat objects for CD4 and CD8 T cells. However, the raw count data are missing. My understanding is that reverse normalization is not possible, and hence generating the count matrices from the normalized data is not possible. Unfortunately,  some tools require the raw count data and don't function with normalized data. Would it be possible to acquire the raw count data?

Snapshots of the "count" and "data" slots:

![image](https://github.com/Coolgenome/TCM/assets/6902136/fded5f3e-96d7-47d2-aaa4-cb832fc62cd9)

**Comment by dustincys** [comment]
Hi @SirKuikka 

Thank you for reaching out. I appreciate your question regarding the count slot in the RNA assay. I would like to clarify that the count slot does indeed contain the raw count information.
 
I would also like to mention that this study comprises both 10x data and a few smartseq data. It is important to note that the raw data in the smartseq cases are not integers. To address this, I recommend either removing the non-integer (**in your images**) cells or utilizing the new normalization technique called "sctransform" function in the latest version of the seurat package.
 
Please let me know if you have any further questions or concerns.

Best

**Comment by SirKuikka** [comment]
Hi @dustincys 

Ok, this explains it.

No further comments.

Thank you.
